"""add feedback fields to pin_requests

Revision ID: add_feedback_fields
Revises: c77de4127a42
Create Date: 2025-01-15 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_feedback_fields'
down_revision = 'c77de4127a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin_requests', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.add_column('pin_requests', sa.Column('feedback_comment', sa.Text(), nullable=True))
    op.add_column('pin_requests', sa.Column('feedback_anonymous', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('pin_requests', sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin_requests', 'feedback_submitted_at')
    op.drop_column('pin_requests', 'feedback_anonymous')
    op.drop_column('pin_requests', 'feedback_comment')
    op.drop_column('pin_requests', 'feedback_rating')
    # ### end Alembic commands ###

