"""empty message

Revision ID: c77de4127a42
Revises: 5a833f7aa912
Create Date: 2025-10-27 12:48:29.631391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77de4127a42'
down_revision = '5a833f7aa912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('categories_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pin_requests',
    sa.Column('pin_requests_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.categories_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('pin_requests_id')
    )
    op.create_table('reports',
    sa.Column('reports_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('reports_id')
    )
    op.create_table('csr_shortlist',
    sa.Column('csr_shortlist_id', sa.Integer(), nullable=False),
    sa.Column('csr_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('shortlisted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csr_id'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['pin_requests.pin_requests_id'], ),
    sa.PrimaryKeyConstraint('csr_shortlist_id')
    )
    op.create_table('match_history',
    sa.Column('match_history_id', sa.Integer(), nullable=False),
    sa.Column('csr_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['csr_id'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['pin_requests.pin_requests_id'], ),
    sa.PrimaryKeyConstraint('match_history_id')
    )
    op.drop_table('pin_request')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pin_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pin_request_pkey'))
    )
    op.drop_table('match_history')
    op.drop_table('csr_shortlist')
    op.drop_table('reports')
    op.drop_table('pin_requests')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
